# numpy

### 1. array

In [1]:
import numpy as np

In [2]:
test_array = np.array(["1","2",5,7],float) #string type으로 입력해도 가능
test_array

array([1., 2., 5., 7.])

In [5]:
type(test_array)

numpy.ndarray

In [6]:
type(test_array[3])

numpy.float64

In [10]:
test_array.ndim #전체차원

1

In [8]:
test_array.shape

(4,)

In [111]:
matrix = [[12,547,7,3],[79,3,79,4],[68,9,3,7]]
np.array(matrix).shape

(3, 4)

In [12]:
np.array(matrix).dtype #데이터의 type 반환

dtype('int32')

### 2. reshape

In [17]:
test_array = [[1,2,3,4],[1,2,5,8]]
np.array(test_array).shape

(2, 4)

In [19]:
test=np.array(test_array)

In [20]:
test.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [21]:
np.array(test).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [24]:
test.reshape(-1,2) #-1 : column기준으로 설정해라. col=2

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [26]:
test.reshape(2,-1) # -1 : row기준으로만. row=2

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [29]:
np.array(matrix).flatten()

array([ 12, 547,   7,   3,  79,   3,  79,   4,  68,   9,   3,   7])

### 3. Indexing & Slicing

In [31]:
test = np.array([[1,2,3],[3,5.6,3.2]], int)
test

array([[1, 2, 3],
       [3, 5, 3]])

In [33]:
test[1][0]

3

In [34]:
test[1,0]

3

In [36]:
test = np.array([
    [1, 2, 5,8], [1, 2, 5,8],[1, 2, 5,8],[1, 2, 5,8]], int)
test

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [37]:
test[:2, :]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [38]:
test[:, 1:3]

array([[2, 5],
       [2, 5],
       [2, 5],
       [2, 5]])

In [39]:
test[:, 2:]

array([[5, 8],
       [5, 8],
       [5, 8],
       [5, 8]])

In [42]:
np.arange(100) #range = np.arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [47]:
a=np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [48]:
a[:,-1] # a의 모든 행, 마지막 열

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [50]:
a[:,-1].reshape(-1,1)

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])

### 4. creation functions

In [55]:
np.arange(0,5.5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

##### ones, zeros & empty

In [56]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
np.zeros(shape=(8,))

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
np.ones(shape=(2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
test

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [64]:
np.zeros_like(test)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [65]:
np.ones_like(test)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [68]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [74]:
np.eye(3,5,2) #np.eye(N=3, M=5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
np.diag(test) #대각행렬

array([1, 2, 5, 8])

In [78]:
np.diag(test, k=2) #대각행렬

array([5, 8])

In [79]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.6168671 , 0.58387146, 0.57727514, 0.39350864, 0.25983185],
       [0.51288052, 0.18975541, 0.51163538, 0.25097992, 0.93599934]])

In [81]:
np.random.normal(0,1,10).reshape(2,5)

array([[-0.46990521,  0.23031117, -1.33245217,  0.02149224, -0.14836054],
       [ 0.13344893,  0.68471682, -2.33051605, -2.43069146, -0.3000574 ]])

### 5. operation functions

In [83]:
test = np.arange(1,11)
test

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
test.sum()

55

In [85]:
test = test.reshape(2,5)
test

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [87]:
test.sum(axis=1)

array([15, 40])

In [89]:
test.sum(axis=0)

array([ 7,  9, 11, 13, 15])

In [112]:
a=np.array([matrix,matrix,matrix])
a

array([[[ 12, 547,   7,   3],
        [ 79,   3,  79,   4],
        [ 68,   9,   3,   7]],

       [[ 12, 547,   7,   3],
        [ 79,   3,  79,   4],
        [ 68,   9,   3,   7]],

       [[ 12, 547,   7,   3],
        [ 79,   3,  79,   4],
        [ 68,   9,   3,   7]]])

In [113]:
np.array(a).sum(axis=0)

array([[  36, 1641,   21,    9],
       [ 237,    9,  237,   12],
       [ 204,   27,    9,   21]])

In [114]:
np.array(a).sum(axis=1)

array([[159, 559,  89,  14],
       [159, 559,  89,  14],
       [159, 559,  89,  14]])

In [115]:
np.array(a).sum(axis=2)

array([[569, 165,  87],
       [569, 165,  87],
       [569, 165,  87]])

In [116]:
test.mean(1)

array([3., 8.])

In [117]:
test.std()

2.8722813232690143

In [118]:
np.exp(test), np.sqrt(test)

(array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
         1.48413159e+02],
        [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
         2.20264658e+04]]),
 array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
        [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766]]))

#### concatenate

In [119]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

In [120]:
np.vstack((a,b)) #세로로

array([[1, 2, 3],
       [2, 3, 4]])

In [121]:
np.hstack((a,b)) #가로로

array([1, 2, 3, 2, 3, 4])

In [125]:
a

array([1, 2, 3])

In [126]:
a.tolist()

[1, 2, 3]

### 6. array operation

In [127]:
a+b

array([3, 5, 7])

In [128]:
a-b

array([-1, -1, -1])

In [129]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

In [130]:
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
test_b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [134]:
test_a.dot(test_b) #행렬곱

array([[ 58,  64],
       [139, 154]])

In [135]:
test_a.transpose() #=test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### 7. comparison

#### all & any
- all : 모두 만족 시 True
- any : 하나라도 만족 시 True

In [137]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [139]:
np.any(a>5), np.any(a<0) 

(True, False)

In [140]:
np.all(a>5) , np.all(a < 10)

(False, True)

In [141]:
a = np.array([1, 3, 0], float)
b = np.array([5, 2, 1], float)
a > b

array([False,  True, False])

In [142]:
a==b

array([False, False, False])

In [143]:
(a>b).any()

True

In [144]:
np.logical_and(a>0, a<3)

array([ True, False, False])

In [145]:
b=np.array([True, False, True])
np.logical_not(b) #반대로

array([False,  True, False])

In [146]:
c=np.array([False, True, False])
np.logical_or(b,c)

array([ True,  True,  True])

In [147]:
a

array([1., 3., 0.])

In [149]:
np.where(a>0) #조건을 만족시키는 index return

(array([0, 1], dtype=int64),)

In [151]:
np.where(a>0,10,-10) #ifelse

array([ 10,  10, -10])

In [153]:
a = np.array([1, np.NaN, np.Inf])
a

array([ 1., nan, inf])

In [154]:
np.isnan(a)

array([False,  True, False])

In [155]:
np.isfinite(a)

array([ True, False, False])

In [157]:
a = np.array([14,22,42,5,8,78,23,35])

In [159]:
np.argmax(a), np.argmin(a) #index return

(5, 3)

In [160]:
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1) , np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

### 8. boolean fancy index

In [162]:
test = np.array([1, 4, 0, 2, 3, 8, 9, 7])

In [163]:
test[test>3] #만족시키는 '값' return

array([4, 8, 9, 7])

In [165]:
condition = test < 3 
test[condition]

array([1, 0, 2])

In [166]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a

array([[ 1.,  4.],
       [ 9., 16.]])

In [167]:
a[b,c] #반드시 b,c integer

array([ 1.,  4., 16., 16.,  4.])