https://github.com/bigdong89/xgboostExtension/blob/master/example/xgbranker_example.py

In [44]:
import numpy as np
from xgboost import XGBRanker

In [52]:
CASE_NUM = 20
GROUPS_NUM = 4
N_FEATURES = 40

# Generate some sample data

In [53]:
X_features = np.random.rand(CASE_NUM, 4)
y = np.random.randint(5, size=CASE_NUM)

print('X shape : ',X_features.shape)
print('y shape : ', y.shape)

X shape :  (20, 4)
y shape :  (20,)


In [56]:
y

array([0, 2, 4, 2, 3, 4, 0, 0, 2, 3, 0, 2, 3, 3, 0, 3, 2, 1, 2, 2])

In [54]:
X_groups = np.arange(0, GROUPS_NUM).repeat(CASE_NUM / GROUPS_NUM)
X_groups

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [55]:
X = np.concatenate([X_groups[:,None], X_features], axis=1)
X

array([[0.        , 0.61375494, 0.32311764, 0.49857142, 0.07062601],
       [0.        , 0.85150663, 0.60744298, 0.95909441, 0.49776913],
       [0.        , 0.15282201, 0.39510237, 0.10642639, 0.84870526],
       [0.        , 0.382086  , 0.37900433, 0.70297225, 0.60393989],
       [0.        , 0.71174958, 0.18102723, 0.02447043, 0.40556017],
       [1.        , 0.83218243, 0.84447364, 0.51376398, 0.20812637],
       [1.        , 0.76781738, 0.96582325, 0.39580535, 0.39218651],
       [1.        , 0.3357081 , 0.667418  , 0.49881297, 0.01926573],
       [1.        , 0.94252453, 0.61917993, 0.7203791 , 0.6895984 ],
       [1.        , 0.54487016, 0.03331689, 0.76425033, 0.48656184],
       [2.        , 0.18188395, 0.17898269, 0.85427315, 0.35681748],
       [2.        , 0.98394567, 0.72063497, 0.83225381, 0.15602933],
       [2.        , 0.80418912, 0.59025661, 0.22479413, 0.52431385],
       [2.        , 0.7680365 , 0.56289993, 0.64317305, 0.22201113],
       [2.        , 0.35808119, 0.

In [58]:
xgb_ranker = XGBRanker(n_estimators = 150, eval_metric=['ndcg'])
xgb.fit(X,y,group = X_groups)

XGBoostError: b'[13:25:48] C:\\Users\\Administrator\\Desktop\\xgboost\\src\\objective\\rank_obj.cc:52: Check failed: gptr.size() != 0 && gptr.back() == info.labels_.Size() group structure not consistent with #rows'